### ISSUE TITLE
a potential java.lang.NumberFormatException bug

### ISSUE THREAD

**Issue by tingsu** [MichaelE1000/yahtzee4android#6]
Hi, we tested this app with an automated GUI testing tool developed by us, and found a potential java.lang.NumberFormatException bug. Here is the adb log:

E/AndroidRuntime( 5883): FATAL EXCEPTION: main
E/AndroidRuntime( 5883): Process: a3e.process, PID: 5883
E/AndroidRuntime( 5883): java.lang.NumberFormatException: Invalid int: "test"
E/AndroidRuntime( 5883):    at java.lang.Integer.invalidInt(Integer.java:137)
E/AndroidRuntime( 5883):    at java.lang.Integer.parse(Integer.java:374)
E/AndroidRuntime( 5883):    at java.lang.Integer.parseInt(Integer.java:365)
E/AndroidRuntime( 5883):    at java.lang.Integer.parseInt(Integer.java:331)
E/AndroidRuntime( 5883):    at java.lang.Integer.<init>(Integer.java:102)
E/AndroidRuntime( 5883):    at com.tum.yahtzee.YahtzeeActivity.play(YahtzeeActivity.java:51)
E/AndroidRuntime( 5883):    at com.tum.yahtzee.YahtzeeActivity$1.onClick(YahtzeeActivity.java:41)
E/AndroidRuntime( 5883):    at android.view.View.performClick(View.java:4444)
E/AndroidRuntime( 5883):    at android.view.View$PerformClick.run(View.java:18445)
E/AndroidRuntime( 5883):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 5883):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5883):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5883):    at android.app.ActivityThread.main(ActivityThread.java:5135)
E/AndroidRuntime( 5883):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5883):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5883):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 5883):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime( 5883):    at dalvik.system.NativeStart.main(Native Method)

This bug can be revealed by direct injection of events (without interaction with the app from the screen) : start the app, enter "non-number" text into the EditText with the title "Amount of Players", and then click the "Play" button. 

After carefully inspecting the source code, we found that despite this EditText is associated with the property android:inputType="number" in the layout file, but the code has not provided proper exception handling to completely avoid this potential exception (see Function "play" in the file "YahtzeeActivity.java"). It would be better to add some "safe code" :)

Here is the code:

 public void play()
    {
        String sPlayers = **playerAmountText.getText().toString()**;
        String sRounds = roundsText.getText().toString();
        if (sPlayers == null || sPlayers.isEmpty() || **new Integer(sPlayers)** == 0 || sRounds == null || sRounds.isEmpty() || new Integer(sRounds) == 0) {
            MessageService.showMessage(YahtzeeActivity.this, "Amount of Rounds and Players must not be zero.");
        } else {
            GameController.get().newGame(new Integer(sPlayers), new Integer(sRounds));
            Intent intent = new Intent(YahtzeeActivity.this, GameActivity.class);
            startActivity(intent);
        }
    }

**Comment by tingsu** [comment]
We confirmed this is a false positive after carefully checking the source code and the layout file. The EditText of Player cannot be input with a String, since its property requires a Number.
